version: 2
jobs:
  Test Ruby 2.3:
    docker:
       - image: circleci/ruby:2.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: CI on Ruby 2.3
          command: ./toys-dev ci
  Test Ruby 2.4:
    docker:
       - image: circleci/ruby:2.4-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: CI on Ruby 2.4
          command: ./toys-dev ci
  Test Ruby 2.5:
    docker:
       - image: circleci/ruby:2.5-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: CI on Ruby 2.5
          command: ./toys-dev ci
  Test Ruby 2.6:
    docker:
       - image: circleci/ruby:2.6-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: CI on Ruby 2.6
          command: ./toys-dev ci
workflows:
  version: 2
  tests:
    jobs:
      - Test Ruby 2.3
      - Test Ruby 2.4
      - Test Ruby 2.5
      - Test Ruby 2.6
